INSERT INTO LocationType (location_type_name) VALUES ('Museum'), ('Private Collection');

INSERT INTO EventType (event_name) VALUES ('Exhibition'), ('Theft'), ('Deterioration'), ('Restration');

INSERT INTO Location (location_name, location_description, placement, date_of_opening, location_type_id) VALUES
('Louvre', 'A national art museum in Paris, France.', 'Musée du Louvre, 75001, Paris, France','1793-08-10', 1),
('The State Hermitage Museum', 'A museum of art and culture in Saint Petersburg, Russia.', '34 Palace Embankment, Dvortsovy Municipal Okrug, Central District, Saint Petersburg, Russia','1764-12-07', 1),
('Deutsches Museum', 'The world''s largest museum of science and technology.', 'Museumsinsel 1, 80538 München, Germany','1903-06-28', 1),
('British Museum', 'A public museum dedicated to human history, art and culture located in the Bloomsbury area of London.', 'Great Russell Street, London WC1B 3DG, England','1757-06-07', 1),
('National Museum of China', 'The national museum of China.', 'No. 16 East Chang''an Street, Dongcheng District, Beijing 100006','2003-02-28', 1),
('Grand Egyptian Museum', 'An archaeological museum, also known as the Giza Museum, under construction in Giza, Egypt.', 'Alexandria Desert Rd, Kafr Nassar, Al Haram, Giza Governorate, Egypt','2023-02-06', 1),
('Minneapolis Institute of Art (Mia)', 'An arts museum located in Minneapolis, Minnesota, United States.', '2400 Third Avenue South Minneapolis, Minnesota','1883-01-01', 1),
('National Museum of Natural History (NMNH)', 'A natural history museum administered by the Smithsonian Institution.', 'National Mall in Washington, D.C., United States','1910-03-17', 1),
('Victoria and Albert Museum (V&A)', 'The world''s largest museum of applied arts, decorative arts and design, housing a permanent collection of over 2.27 million objects.', 'Cromwell Road, Kensington and Chelsea, London, SW7','1857-06-20', 1),
('Metropolitan Museum of Art (the Met)', 'The largest art museum in the Americas and fourth-largest in the world.', '1000 Fifth Avenue (The Met Fifth Avenue) 99 Margaret Corbin Drive (The Cloisters) New York City, U.S.','1870-04-13', 1),
('Art Institute of Chicago', 'Internationally regarded as one of the best art schools and top fine arts colleges in the US.', '111 South Michigan Avenue Chicago, Illinois 60603, U.S.', '1870-11-22', 1),
('Louvre Abu Dhabi', 'An art museum located on Saadiyat Island in Abu Dhabi.', 'Saadiyat Island, Abu Dhabi, United Arab Emirates', '2017-11-08', 1),
('National Gallery of Art', 'An art museum in Washington, D.C., United States.', 'National Mall between 3rd and 9th Streets at Constitution Avenue N.W., Washington, D.C., U.S.', '1941-03-17', 1),
('The Beyeler Foundation', 'A museum in Switzerland owns and oversees the art collection of Hildy and Ernst Beyeler, which features modern and traditional art.', 'Riehen, Switzerland', '1997-10-18', 1),
('Geneva Freeport', 'A warehouse complex for the storage of art and other valuables and collectibles.', 'Geneva, Switzerland', '1888-01-01', 2),
('The Kunsthaus Zürich', 'The biggest art museum of Switzerland and one of the most important art collections in Switzerland, assembled over time by the local art association called Zürcher Kunstgesellschaft.', 'Heimplatz 1, 8001 Zürich', '1910-04-17', 1),
('Wynn Las Vegas', 'A luxury resort and casino.', '3131 South Las Vegas Boulevard, Paradise, Nevada, U.S.', '2005-04-28', 2),
('Musee d''Art Moderne de Paris or MAM Paris', 'A major municipal museum dedicated to modern and contemporary art of the 20th and 21st centuries.', 'Palais de Tokyo, 11 avenue du Président Wilson, 75016 Paris, France', '1961-08-06', 1),
('The Mohamed Mahmoud Khalil Museum', 'The museum is dedicated to the memory of Mohammed Mahmoud Khalil Pasha and his wife Emiline Lock.', 'Giza, Egypt', '1962-07-23', 1),
('Momart', 'A British company specialising in the storage, transportation, and installation of works of art.', 'London, England', '1972-09-25', 2),
('The Broad', 'A contemporary art museum on Grand Avenue in Downtown Los Angeles.', '221 South Grand Avenue, Los Angeles, California, United States', '2015-09-20', 1),
('The Andy Warhol Museum', 'It is the largest museum in North America dedicated to a single artist.', '117 Sandusky Street
Pittsburgh, Pennsylvania, USA', '1994-05-13', 1),
('The Pushkin State Museum of Fine Arts', 'The largest museum of European art in Moscow.', '12, Volkhonka Street, Khamovniki, Moscow, Russia', '1912-05-31', 1),
('The Courtauld Gallery', 'An art museum in Somerset House, on the Strand in central London.', 'Somerset House, Strand, London WC2R 0RN, Великобритания', '1932-04-21', 1),
('Palazzo Grassi or Palazzo Grassi-Stucky', 'Since 2006, Palazzo Grassi has been presenting temporary exhibitions from the Pinault Collection.', 'Campo San Samuele, 3231, 30124 Venezia VE, Italy', '1772-06-15', 2),
('Whitney Museum of American Art', 'A modern and contemporary American art museum located in the Meatpacking District and West Village neighborhoods of Manhattan in New York City.', '99 Gansevoort Street, Lower Manhattan, New York City', '1931-11-18', 1),
('The Brant Foundation Art Study Center', 'A private art collection and gallery with exhibition spaces.', '941 North Street Greenwich, CT, US', '2009-05-09', 2),
('Gagosian Gallery', 'A contemporary art gallery.', 'New York City', '1989-02-03', 2),
('Munch Museum', 'An art museum dedicated to the life and works of the Norwegian artist Edvard Munch.', '	Oslo, Norway', '1963-05-29', 1),
('Museum of Modern Art (MoMA)', 'MoMA is the first American museum devoted exclusively to modern art', '11 West 53rd Street, Manhattan, New York City, U.S.', '1929-11-07', 1);

INSERT INTO Owner (owner_name, owner_description) VALUES
('Louvre', 'A national art museum in Paris, France.'),
('The State Hermitage Museum', 'A museum of art and culture in Saint Petersburg, Russia.'),
('Steve Wynn', 'American real estate developer and art collector'),
('Steven A. Cohen', 'American billionaire businessman'),
('Ezra and David Nahmad', 'Art collectors and dealers'),
('Kenneth Cordele Griffin', ' American hedge fund manager, entrepreneur and investor'),
('The David Geffen Foundation', 'Private foundation located in Los Angeles'),
('Alexander Parish & Robert B. Simon', 'A consortium of art dealers'),
('Saudi Arabian culture ministry', 'The cultural sector in the Kingdom of Saudi Arabia'),
('Yves Bouvie', 'Swiss businessman and art dealer'),
('Dmitry Yevgenyevich Rybolovlev', 'Russian oligarch, billionaire businessman, and investor'),
('David Rockefeller', 'American investment banker'),
('Metropolitan Museum of Art (the Met)', 'The largest art museum in the Americas and fourth-largest in the world'),
('Musee d''Art Moderne de Paris or MAM Paris', 'A major municipal museum dedicated to modern and contemporary art of the 20th and 21st centuries'),
('The Mohamed Mahmoud Khalil Museum', 'The museum is dedicated to the memory of Mohammed Mahmoud Khalil Pasha and his wife Emiline Lock'),
('Charles Saatchi', 'Iraqi-British businessman'),
('Eli and Edythe Broad', 'Philanthropists, founders of The Broad Foundations'),
('The Mayers', 'Collectors of postwar and contemporary American art, impressionism, European modernism, Chinese ceramics, and African and Oceanic figures'),
('Stefan Edlis', 'Austrian born American art collector and philanthropist'),
('Cherise Moueix', 'French winemaker'),
('Stavros Niarchos', 'Greek billionaire, shipping magnate'),
('Francois Pinault', 'French billionaire businessman'),
('The Pushkin State Museum of Fine Arts', 'The largest museum of European art in Moscow'),
('Whitney Museum of American Art', 'A modern and contemporary American art museum located in the Meatpacking District and West Village neighborhoods of Manhattan in New York City'),
('Peter Mark Brant Sr.', 'American industrialist and art collector'),
('Masao Wanibuchi', 'Japan tailor and collector'),
('Philip Niarchos', 'Greek billionaire, the eldest son of the Stavros Niarchos'),
('Foundation of Thomas and Doris Ammann', 'Switzerland charity Foundation'),
('Larry Gagosian', 'American art dealer'),
('Samuel Irving "S.I." Newhouse Jr.', 'American heir to a substantial magazine and media business'),
('Munch Museum', 'An art museum'),
('Andy Warhol', 'American visual artist, film director, producer, and leading figure in the pop art movement');


INSERT INTO Author (author_name, author_description, author_date_of_birth) VALUES
('Vincent Willem van Gogh', 'Dutch Post-Impressionist painter', '30 March 1853'),
('Edvard Munch', 'Norwegian painter and printmaker', '12 December 1863'),
('Yayoi Kusama', 'Japanese contemporary artist', '22 March 1929'),
('Louise Josephine Bourgeois', 'French-American artist', '25 December 1911'),
('Louise Nevelson', 'American sculptor', '23 September 1899'),
('Marie-Françoise Constance Mayer La Martiniere', 'French painter of portraits, allegorical subjects, miniatures and genre works', '9 March 1775'),
('Elisabeth Sophie Cheron', 'French painter, poet, musician, artist, and academician', '3 October 1648'),
('Jackson Pollock', 'American painter in the abstract expressionist movement', '28 Janurary 1912'),
('Eugene Henri Paul Gauguin', 'French painter, sculptor, printmaker, ceramist, and writer', '7 June 1848'),
('Leonardo di ser Piero da Vinci', 'Italian painter, draughtsman, engineer, scientist, theorist, sculptor, and architect of the High Renaissance', '15 April 1452'),
('Willem de Kooning', 'Dutch-American abstract expressionist artist', '24 April 1904'),
('Tracey Karima Emin', 'An English artist known for autobiographical and confessional artwork', '3 July 1963'),
('Andy Warhol', 'American visual artist, film director, producer, and leading figure in the pop art movement', '6 August 1928'),
('Mark Rothko', 'Latvian-born American abstract painter', '25 February 1903'),
('Pablo Ruiz Picasso', 'Spanish painter, sculptor, printmaker, ceramicist, and theatre designer', '1881-10-25'),
('Rudolf Stingel', 'Italian artist', '1956-05-26'),
('Raffaello (Raphael) Sanzio da Urbino', ' Italian painter and architect of the High Renaissance', '1483-03-28');

INSERT INTO ArtObject (author_id, art_object_name, art_object_description, current_owner_id, current_location_id, date_of_creation) VALUES
(7, 'Autoportrait', 'Self-portrait made in oil on canvas 88 x 73 cm.', 1, 1, '1672'),
(1, 'Portrait de Vincent van Gogh', 'Van Gogh''s last self-portrait, painted shortly before he left Saint-Rémy-de-Provence in southern France', 1, 1, '1902'),
(1, 'Peasant Woman Against a Background of Wheat', 'This Painting was painted by Vincent van Gogh in 1890.It is one of the most expensive paintings of all time.', 1, 1, '1890'),
(8, 'Number 17A', 'An abstract painting featuring a kaleidoscope of colors across a fiberboard canvas', 5, 11, '1948'),
(11,'Interchange', 'An abstract expressionist oil painting on canvas', 6, 11, '1955'),
(10, 'Salvator Mundi', '''Salvator Mundi  is a painting of the most iconic figure in the world by the most important artist of all time,'' says Loic Gouzer', 9, 12, '1490-1500'),
(9, 'Bathers', 'This image of bathers in an exotic landscape of fiery hues was painted on Gauguin''s second trip to Tahiti.', 4, 13, '1902'),
(15, 'The Small Pierrot with Flowers', 'Instilled with a sense of personal charm, this delightful image conveys Picasso''s son Paulo dressed as a pierrot.', 5, 15, '1960'),
(15, 'Young Girl with a Flower Basket', 'The painting depicts a Parisian street girl, named "Linda", whose fate is unknown.', 5, 15, '1905'),
(15, 'The Dream', 'An oil on canvas painting by Pablo Picasso, then 50 years old, portraying his 22-year-old mistress Marie-Thérèse Walter.', 4, 13, '1932'),
(15, 'The Actor', 'The painting illustrates a shift in Picasso''s artistic approach, which was influenced by his meeting of his new partner, Fernande Olivier in 1904.', 13, 10, '1904-1905'),
(15, 'Pigeon with peas or Dove with green peas', 'It is an example of Picasso''s Cubist works and has an estimated value of €23 million.', 14, 18, '1911'),
(1, 'Poppy Flowers or Vase And Flowers or Vase with Viscaria', 'The painting serves as a testament to Van Gogh''s profound respect for Adolphe Monticelli, an established painter whose work greatly impacted him during his time in Paris in 1886.', 15, 19, '1887'),
(12, 'Everyone I Have Ever Slept With 1963–1995 or The Tent', 'The work was a tent with the appliqued names of, literally, everyone she had ever slept with (not necessarily had sex with)', 16, 20, '1995'),
(13, 'Mao', 'Warhol melded his signature style with the scale of totalitarian propaganda to address the cult of personality surrounding the Chinese ruler Mao Zedong.', 17, 21, '1973'),
(13, 'Campbell''s Soup Can', 'The painting have become synonymous with the Pop art movement.', 17, 21, '1962'),
(13, 'Liz [Early Colored Liz]', 'The painting is included in a series of thirteen canvases, each with the same image of Taylor set before a jewel-toned background.', 17, 21, '1963'),
(13, 'Turquoise Marilyn', 'Warhol actually painted five colored Marilyns in 1964 with different colored backgrounds: red, orange, light blue, sage blue, and turquoise.', 4, 13, '1964'),
(14, 'No. 6 or Violet, Green and Red', 'In common with Rothko''s other works from this period, No. 6 consists of large expanses of colour delineated by uneven, hazy shades.', 11, 30, '1951'),
(15, 'Harlequin and Companion', 'The image of Harlequin passes through the works by Pablo Picasso. He first turned to the circus theme in 1900 (Pierrot and Colombina), around the same time, when he first came to Paris.', 23, 23, '1901'),
(15, 'Harlequin', 'By 1901 Harlequin was a ubiquitous figure in popular culture. Picasso gave his Harlequin the attributes of Pierrot: a white face and ruffs.', 13, 10, '1901'),
(15, 'Absinthe Drinker', 'Picasso produced this work in the autumn of 1901, during his second trip to Paris, when he was just 22 years old.', 2, 2, '1901'),
(15, 'Yo, Picasso', 'It is a self-portrait of the artist that depicts him in his youth, aged 19.', 21, 25, '1901'),
(16, 'Untitled (Madonna)', 'The painting is painted on linen. It depicts a statuesque, meticulously structured Virgin Mary gazing skywards.', 22, 25, '2009'),
(16, 'Untitled, 2012 (Franz West)', 'The painting of Franz West, the recently deceased Viennese sculptor and Stingel’s close friend, stands out as examples of the emotional richness. Strewn with splashes, this portrait escape the rhetoric of commemoration and self-regard.', 22, 25, '2012'),
(16, 'Untitled (After Sam)', 'Untitled (After Sam) is part of a series of photo-realistic paintings based on black-and-white photographs of Rudolf Stingel taken by artist Sam Samore, who is referenced in the title of this work.', 24, 26, '2005–2006'),
(16, 'Untitled (St John)', 'The painting is part of a series of paintings showing different medieval sculptures, begun by enlarging original photos and finished by hand.', 22, 25, '2009'),
(16, 'Untitled (Paula)', 'In a monumental painting—three metres high and four metres long—a woman sits with her head against the wall, coolly smoking, lost in her thoughts.', 22, 25, '2012'),
(16, 'Untitled 2012', 'An old, worn photographic portrait of the artist, shirt open, lost in thought. The artist exclusively uses painting, reproducing the smallest detail with precision, down to the watermarks left by glasses on the original photograph.', 22, 25, '2012'),
(3, 'Longing for Eternity', 'Kusama''s Infinity Mirror Rooms create phenomenological experiences that provoke a sense of boundlessness and transcendence.', 17, 21, '2017'),
(13, 'Blue Shot Marilyn', 'Warhol actually painted five colored Marilyns in 1964 with different colored backgrounds: red, orange, light blue, sage blue, and turquoise.', 25, 27, '1964'),
(13, 'Shot Red Marilyn', 'Warhol actually painted five colored Marilyns in 1964 with different colored backgrounds: red, orange, light blue, sage blue, and turquoise.', 27, 25, '1964'),
(13, 'Shot Sage Blue Marilyn', 'Warhol actually painted five colored Marilyns in 1964 with different colored backgrounds: red, orange, light blue, sage blue, and turquoise.', 29, 28, '1964'),
(13, 'Orange Marilyn', 'Warhol actually painted five colored Marilyns in 1964 with different colored backgrounds: red, orange, light blue, sage blue, and turquoise.', 6, 11, '1964'),
(12, 'Madonna', 'The painting is a highly unusual representation, this painting might be of the Virgin Mary.', 31, 29, '1892-1895'),
(10, 'Madonna Litta', 'The Madonna Litta might be one of the paintings of the Madonna and Child recorded in Leonardo''s studio before or during his first Milanese period.', 2, 2, '1490'),
(17, 'Conestabile Madonna', 'It was likely the last work painted by Raphael in Umbria before moving to Florence.', 2, 2, '1502–1504');


INSERT INTO Event (event_name,event_type_id, event_description, event_start_date, event_end_date, event_location_id, event_price) VALUES
(NULL, 4, 'The piece was in poor shape. The dealers took the work to renowned art restorer Dianne Modestini, who oversaw the support''s reconstruction and then stripped the overpainting and filled in missing parts.', '2005-04-11', '2011-11-20', 12, NULL),
('The Art of Paul Gauguin', 1, '280 catalogued works were an encyclopedic survey of Paul Gauguin''s achievements not only in painting but also in carving, sculpture, ceramics, prints, and illustrated books.', '1988-09-17', '1988-12-11', 11, NULL),
('The Art of Paul Gauguin', 1, '280 catalogued works were an encyclopedic survey of Paul Gauguin''s achievements not only in painting but also in carving, sculpture, ceramics, prints, and illustrated books.', '1988-05-01', '1988-07-31', 13, NULL),
('Paul Gauguin', 1, 'The exhibition shows Gauguin''s diverse self-portraits as well as the visionary and spiritual images from his time in Brittany.', '2015-02-08', '2015-06-28', 14, NULL),
('Miro, Monet, Matisse – The Nahmad Collection', 1, 'A portion of the impressive art collection of the art-dealing Nahmad family went on display at the Kunsthaus Zurich modern art museum.', '2011-10-21', '2012-01-15', 16, NULL),
(NULL, 3, 'While showing the painting to reporters, Steve Wynn accidentally elbowed it, creating a significant tear.', '2006-10-21', '2006-10-21', 17, NULL),
(NULL, 3, 'A woman accidentally fell into the painting on exhibit. The fall created a rip of about 15 centimeters in height. The damage was restored in April 2010 after three months of work.', '2010-01-25', '2010-01-25', 10, NULL),
(NULL, 2, 'A masked burglar broke into the Paris Museum of Modern Art by removing the glass from a window. The painting was one of five artworks stolen from the MAM Paris.', '2010-05-20', '2010-05-20', 18, NULL),
(NULL, 2, 'The painting had been stolen from Cairo''s Mohamed Mahmoud Khalil Museum in 1977, and was recovered ten years later in Kuwait.', '1977-06-04', '1987-08-05', 19, NULL),
(NULL, 2, 'The painting was stolen again from the same museum in August 2010. Subsequently, it was suggested that the stolen painting was a copy of the original stolen in 1977, and that in fact, after the first theft, the original was not returned to the museum.', '2010-08-14', '2010-08-14', 19, NULL),
(NULL, 3, 'In 2004, the tent was destroyed in a fire at the East London Momart warehouse, along with two of Emin''s other works and 100 more from Saatchi''s collection, including works by Hirst, Jake and Dinos Chapman and Martin Maloney.', '2004-05-24', '2004-05-24', 20, NULL),
('Expansive Presentation of Andy Warhol', 1, 'An in-depth installation of Andy Warhol opened May 26, 2021, features 26 works. The exhibition is still active.', '2021-05-26', NULL, 21, NULL),
('Becoming Picasso: Paris 1901', 1, 'This exhibition tells the remarkable story of Pablo Picasso’s breakthrough year as an artist – 1901.  It was the year that the highly ambitious nineteen-year-old first launched his career in Parisat.', '2013-02-14', '2013-05-26', 24, NULL),
('Rudolf Stingel', 1, 'A solo exhibition curated by the artist in collaboration with Elena Geuna.', '07 April 2013', '31 December 2013', 25, NULL),
('Rudolf Stingel', 1, 'Employing such materials as rubber, carpet, painted aluminum, Styrofoam, and paint, Rudolf Stingel''s work questions and disrupts the viewer''s understanding and experience of an art object.', '2007-06-28', '2007-10-14', 26, NULL),
('Where are we going?', 1, 'First official exhibition of the Pinault Collection.', '2006-04-18', '2006-10-01', 25, NULL),
('Yayoi Kusama: Infinity Mirrors', 1, 'The exibition provided the unique opportunity to experience six infinity rooms—the artist''s most iconic kaleidoscopic environments—alongside large-scale installations and key paintings, sculptures and works on paper from the early 1950s to 2017.', '2017-10-21', '2018-01-01', 21, NULL),
('Oscar the Grouch', 1, 'It is a major solo exhibition by Urs Fischer. With two major installations dramatically altering the architecture of the Study Center’s galleries, Oscar the Grouch marks the first-ever solo exhibition in the Greenwich space in dramatic fashion.', '2010-05-15', '2011-01-03', 27, NULL),
(NULL, 2, 'The version owned by the Munch Museum of Oslo was stolen in 2004, but recovered two years later in 2006.', '1990-03-29', '1990-06-22', 29, NULL);


INSERT INTO EventObjects (event_id, art_object_id) VALUES
(19, 34),
(18, 30),
(17, 29),
(16, 37), (16, 27),
(15, 26),
(14, 25), (14, 24), (14, 27),
(13, 22), (13, 20), (13, 21),
(12, 17), (12, 16), (12, 15),
(11, 14),
(10, 13),
(9, 13),
(8, 12),
(7, 11),
(6, 10),
(5, 8),
(4, 7),
(3, 7),
(2, 7),
(1, 6);

INSERT INTO Purchase (purchase_date,art_object_id ,purchase_price, seller_id, buyer_id) VALUES
('2013-05-01', 6, 83000000, 8, 10),
('2013-05-02', 6, 127500000, 10, 11),
('2017-11-15', 6, 450312500, 11, 9),
('2015-09-18', 5, 300000000, 7, 6),
('2005-10-07', 3, 47500000, 3, 4),
('2005-10-07', 7, 52500000, 3, 4),
('2018-05-08', 9, 115000000, 12, 5),
('2013-03-26', 10, 155000000, 3, 4),
('2011-05-12', 17, 26962500, 18, 17),
('2007-05-20', 18, 80000000, 19, 4),
('2014-09-13', 19, 186000000, 20, 11),
('1967-07-11', 31, 5000, 32, 25),
('1994-11-02', 32, 3600000, 26, 27),
('2022-05-02', 33, 195000000, 28, 29),
('2017-10-30', 34, 200000000, 30, 6);
